In [15]:
import tensorflow as tf

# Variable take the input as the tensor and output as the variable

my_var = tf.Variable(tf.zeros([2, 3]))
my_var

<tf.Variable 'Variable_11:0' shape=(2, 3) dtype=float32_ref>

In [16]:
sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)

Placeholder are just holding the position for data to be fed into the graph. Placeholder get data from the ```feed_dict```argument in the session. To put the placeholder in to graph, we must perform at least one operation on the placeholder


In [17]:
import numpy as np

sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2, 3])
y = tf.identity(x)
x_vals = np.random.rand(2, 3)
sess.run(y, feed_dict={
    x: x_vals
})

array([[ 0.09885034,  0.52797729,  0.19599575],
       [ 0.87936419,  0.74497867,  0.81299829]], dtype=float32)

In Tensorflow, when using the variable in graph we must initial them with the ```tf.global_variables_initializer()``` method. But if we want to initialize a variable based result of initializing of another variable, we have to initialize variables in the order we want as follows:

In [34]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([3, 3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.ones_like(first_var))
sess.run(second_var.initializer)

print(sess.run(second_var))
print(sess.run(first_var))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
