In [1]:
import tensorflow as tf
sess = tf.Session()

In [2]:
# ReLU activation function
# Build in
x = [-3.0, 3.0, 10.0]
print(sess.run(tf.nn.relu(x)))

# Manually
x_relu = [max(0, i) for i in x]
print(sess.run(tf.convert_to_tensor(x_relu)))

[  0.   3.  10.]
[  0.   3.  10.]


In [3]:
# ReLU6 activation function
print(sess.run(tf.nn.relu6(x)))

# Manually
x_relu6 = [min(max(0, i), 6) for i in x]
print(sess.run(tf.convert_to_tensor(x_relu6)))

[ 0.  3.  6.]
[ 0.  3.  6.]


In [4]:
# Sigmoid function
print(sess.run(tf.nn.sigmoid(x)))
# Manually
x_sigmoid = [tf.truediv(1.0, tf.add(1.0, tf.exp(-i))) for i in x]

print(sess.run(x_sigmoid))

[ 0.04742587  0.95257413  0.99995458]
[0.047425874, 0.95257413, 0.99995458]


In [5]:
# Tanh activation function
# build in
print(sess.run(tf.nn.tanh(x)))
# manually
x_tanh = [tf.truediv(tf.subtract(tf.exp(i), tf.exp(-i)), tf.add(tf.exp(i), tf.exp(-i))) for i in x]
print(sess.run(x_tanh))

[-0.99505472  0.99505472  1.        ]
[-0.99505472, 0.99505472, 1.0]


In [6]:
# The softsign function
print(sess.run(tf.nn.softsign(x)))
# Manually
x_softsign = tf.truediv(x, tf.add(tf.abs(x), 1))
print(sess.run(x_softsign))

[-0.75        0.75        0.90909094]
[-0.75        0.75        0.90909094]


In [7]:
# Soft plus activation function
print(sess.run(tf.nn.softplus(x)))
# Manually
x_softplus = tf.log(tf.exp(x) + 1)
print(sess.run(x_softplus))

[  0.04858733   3.04858732  10.00004578]
[  0.04858733   3.04858732  10.00004578]


In [8]:
# ELU activation function
print(sess.run(tf.nn.elu(x)))
# Manually
x_elu = []
for i in x:
    if i < 0:
        x_elu.append(tf.exp(i) - 1)
    else:
        x_elu.append(i)
print(sess.run(tf.convert_to_tensor(x_elu)))

[ -0.95021296   3.          10.        ]
[ -0.95021296   3.          10.        ]


In [10]:
# Softmax
print(sess.run(tf.nn.softmax(x)))

[  2.25826511e-06   9.11049196e-04   9.99086738e-01]


In [18]:
print(sess.run(tf.nn.sigmoid(0.7683)))

0.683153
