In [3]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

In [34]:
identity_matrix = tf.diag([1.0, 2.0, 3.5])
A = tf.truncated_normal([2, 3])
B = tf.fill([2, 3], 4.5)
C = tf.random_uniform([3, 2])
D = tf.convert_to_tensor([
    [1.0, 3.0], [3.0, 4.0]
])

In [35]:
sess.run(D)

array([[ 1.,  3.],
       [ 3.,  4.]], dtype=float32)

In [36]:
# Addition and subtraction 
print(sess.run(A + B))

[[ 5.20643806  4.99972725  3.88283706]
 [ 3.22123408  4.09523058  4.49026108]]


In [37]:
print(sess.run(B - B))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [38]:
print identity_matrix.shape
print B.shape
print(sess.run(tf.matmul(B, identity_matrix)))

(3, 3)
(2, 3)
[[  4.5    9.    15.75]
 [  4.5    9.    15.75]]


In [42]:
# Inverse the matrix
E = tf.matrix_inverse(D)
print(sess.run(E))
# Test again
print(sess.run(tf.matmul(D, E)))

[[-0.80000007  0.60000002]
 [ 0.60000002 -0.20000002]]
[[ 1.  0.]
 [ 0.  1.]]


In [58]:
# Eigenvalues of a matrix

eigens = tf.self_adjoint_eig(D)
print(sess.run(eigens[0]))

# Testing again
print(sess.run(tf.matmul(D, eigens[1])))

print(sess.run(tf.multiply(eigens[0], eigens[1])))

[-0.85410208  5.85410213]
[[ 0.72654241 -3.07768369]
 [-0.44902825 -4.97979641]]
[[ 0.72654265 -3.07768345]
 [-0.44902802 -4.97979689]]
