In [1]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

In [3]:
x_shape = [1, 4, 4, 1]
x_val = np.random.uniform(size=x_shape)

In [5]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [9]:
print(x_val.shape)

(1, 4, 4, 1)


In [8]:
print(sess.run(tf.convert_to_tensor(x_val)))

[[[[ 0.25090896]
   [ 0.13133066]
   [ 0.5548951 ]
   [ 0.03543313]]

  [[ 0.0776131 ]
   [ 0.68297153]
   [ 0.66192017]
   [ 0.76731463]]

  [[ 0.18942319]
   [ 0.11247973]
   [ 0.20740246]
   [ 0.32259955]]

  [[ 0.38538169]
   [ 0.81473545]
   [ 0.55720771]
   [ 0.28550542]]]]
